# Generated by Django 2.0.2 on 2018-02-21 20:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BreastDiagnosisData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('age', models.IntegerField(default=18)),
                ('tumor_size_in_mm', models.IntegerField()),
                ('tumor_grade', models.IntegerField()),
                ('er_status', models.CharField(max_length=64)),
                ('pr_status', models.CharField(max_length=64)),
                ('her2_status', models.CharField(max_length=64)),
                ('num_pos_nodes', models.IntegerField(default=0)),
                ('ethnicity', models.CharField(max_length=64)),
                ('sex', models.CharField(default='Female', max_length=64)),
                ('type', models.CharField(max_length=64)),
                ('site', models.CharField(blank=True, max_length=64, null=True)),
                ('laterality', models.CharField(max_length=64)),
                ('stage', models.CharField(blank=True, max_length=64, null=True)),
                ('number_of_tumors', models.IntegerField(blank=True, default=0, null=True)),
                ('region', models.CharField(blank=True, default='unk', max_length=64, null=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='breast_diagnoses', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
