# Generated by Django 2.0.2 on 2018-02-22 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='breastdiagnosisdata',
            name='tumor_size',
            field=models.CharField(blank=True, default='<1cm', max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='breastdiagnosisdata',
            name='tumor_size_in_mm',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
