# Generated by Django 2.0.2 on 2018-02-22 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_auto_20180222_0539'),
    ]

    operations = [
        migrations.AlterField(
            model_name='breastdiagnosisdata',
            name='site',
            field=models.CharField(blank=True, default='Upper-Outer', max_length=64, null=True),
        ),
    ]
