# Generated by Django 2.0.2 on 2018-03-05 00:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_prostatediagnosisdata_age'),
    ]

    operations = [
        migrations.RenameField(
            model_name='prostatediagnosisdata',
            old_name='tumor_size_in_mm',
            new_name='tumor_size_mm',
        ),
    ]
